-   id: custom-hook
    name: custom-hook
    description: This is a custom hook.
    entry: https://github.com/darshan-num/git-hooks-poc/blob/githook/hook.py
    language: python
    language_version: python3.6
