-   id: validate-branch-name
    name: Branch checker
    description: Checks if the branch name corresponds to a valid task.
    entry: validate-branch-name
    language: python
    always_run: true
    stages: [commit]
